services:
  server:
    image: server:06
    container_name: server
    build: .

  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
