FROM nginx:latest

RUN apt update && apt install -y gcc spawn-fcgi libfcgi-dev
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./server.c /server.c
COPY ./start.sh /start.sh

ENTRYPOINT ["bash", "./start.sh"]
